from configs import PROJECT_DATA_DIR
from services.generator import generate_response

_RESUME_PATH = PROJECT_DATA_DIR.joinpath("resume.md")


def _load_resume() -> str:
    return _RESUME_PATH.read_text(encoding="utf-8")


def _extract_section(resume: str, header: str, next_header: str | None = None) -> str:
    """Extract a markdown section by its header text."""
    start = resume.find(f"# {header}")
    if start == -1:
        return ""
    if next_header:
        end = resume.find(f"# {next_header}", start)
        return resume[start:end].strip() if end != -1 else resume[start:].strip()
    return resume[start:].strip()


def generate_header(resume: str) -> str:
    """Return static contact/header block (everything before the first section)."""
    first_section = resume.find("\n# ")
    return resume[:first_section].strip()


def generate_summary(resume: str, job_description: str) -> str:
    """Tailor the professional summary to the job description."""
    original = _extract_section(resume, "Resume Summary", "CAREER HIGHLIGHTS")
    prompt = (
        "You are a professional resume writer. Tailor the resume summary below for the "
        "job description provided. Keep it 3–5 sentences, impact-focused, and specific "
        "to the role. Return only the summary text with no markdown headers.\n\n"
        f"ORIGINAL SUMMARY:\n{original}\n\n"
        f"JOB DESCRIPTION:\n{job_description}"
    )
    return f"# Resume Summary\n{generate_response(prompt)}"


def generate_highlights(resume: str, job_description: str) -> str:
    """Select and refine the most relevant career highlights for the role."""
    original = _extract_section(resume, "CAREER HIGHLIGHTS", "CORE COMPETENCIES")
    prompt = (
        "You are a professional resume writer. From the career highlights below, "
        "select and refine the 5–7 most relevant bullet points for the job description. "
        "Keep each point quantified and impactful. Return only bullet points.\n\n"
        f"ORIGINAL HIGHLIGHTS:\n{original}\n\n"
        f"JOB DESCRIPTION:\n{job_description}"
    )
    return f"# CAREER HIGHLIGHTS\n{generate_response(prompt)}"


def generate_competencies(resume: str, job_description: str) -> str:
    """Reorder and tailor core competencies to best match the role."""
    original = _extract_section(resume, "CORE COMPETENCIES", "AWARDS & RECOGNITION")
    prompt = (
        "You are a professional resume writer. Tailor the core competencies below to "
        "best align with the job description. Prioritize relevant skills; reorder or "
        "trim as needed. Return only the competencies content with no top-level header.\n\n"
        f"ORIGINAL COMPETENCIES:\n{original}\n\n"
        f"JOB DESCRIPTION:\n{job_description}"
    )
    return f"# CORE COMPETENCIES\n{generate_response(prompt)}"


def generate_experience(resume: str, job_description: str) -> str:
    """Tailor work experience bullet points to the job description."""
    original = _extract_section(resume, "WORK EXPERIENCE", "CERTIFICATION/TRAINING")
    prompt = (
        "You are a professional resume writer. Tailor the work experience below for the "
        "job description. Retain all roles but prioritize and refine bullet points that "
        "are most relevant. Use strong action verbs and preserve quantified achievements. "
        "Return the formatted experience section without a top-level header.\n\n"
        f"ORIGINAL EXPERIENCE:\n{original}\n\n"
        f"JOB DESCRIPTION:\n{job_description}"
    )
    return f"# WORK EXPERIENCE\n{generate_response(prompt)}"


def generate_awards(resume: str) -> str:
    """Return the awards & recognition section as-is (static)."""
    return _extract_section(resume, "AWARDS & RECOGNITION", "WORK EXPERIENCE")


def generate_certifications(resume: str) -> str:
    """Return the certifications section as-is (static)."""
    return _extract_section(resume, "CERTIFICATION/TRAINING", "EDUCATION")


def generate_education(resume: str) -> str:
    """Return the education section as-is (static)."""
    return _extract_section(resume, "EDUCATION")


class ResumeAgent:
    def __init__(self):
        self._resume = _load_resume()

    def prepare_resume(self, job_description: str) -> str:
        """
        Prepare a resume tailored to the given job description.
        Each section is generated by a dedicated function and then assembled.
        """
        sections = [
            generate_header(self._resume),
            generate_summary(self._resume, job_description),
            generate_highlights(self._resume, job_description),
            generate_competencies(self._resume, job_description),
            generate_awards(self._resume),
            generate_experience(self._resume, job_description),
            generate_certifications(self._resume),
            generate_education(self._resume),
        ]
        resume = "\n\n".join(s for s in sections if s)
        print(resume)
        return resume
