from .inputs import SKILLS, SCOPE, PREFERRED_LOCATIONS, SOURCES, JOBS_PER_SOURCE, MAX_PAGES, HEADLESS, LOGIN_WAIT_SECONDS, LINKEDIN_CREDENTIALS
__all__ = [
    "SKILLS",
    "SCOPE",
    "PREFERRED_LOCATIONS",
    "SOURCES",
    "JOBS_PER_SOURCE",
    "MAX_PAGES",
    "HEADLESS",
    "LOGIN_WAIT_SECONDS",
    "LINKEDIN_CREDENTIALS",
]